id: A505504F3
title: 'Dispelling the Anguish of Existence and Quiescence: A Prayer of Calling the
  Guru from Afar'
type: translation
pechas:
- I9574D9A5
- I9A4E0E2B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:09:13.163925
  last_modified_at: 2023-01-04 12:09:13.163945
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I9574D9A5/EAA1: 49BC
  I9A4E0E2B/6366: 49BC
